import {createServer} from "node:net";
import {spawn} from "node:child_process";
import {mkdir,readFile} from "node:fs/promises";
import {existsSync} from "node:fs";
import assert from "node:assert/strict";
if(!process.env.PLAYWRIGHT_BROWSERS_PATH&&existsSync("work/playwright-browsers"))process.env.PLAYWRIGHT_BROWSERS_PATH=`${process.cwd()}/work/playwright-browsers`;
const {chromium,webkit}=await import("@playwright/test");
const portProbe=createServer();
await new Promise(resolve=>portProbe.listen(0,"127.0.0.1",resolve));
const port=portProbe.address().port;
await new Promise(resolve=>portProbe.close(resolve));
const server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","--hostname","127.0.0.1","--port",String(port)],{stdio:"ignore"});
const origin=`http://127.0.0.1:${port}`;
try {
 let ready=false;
 for(let attempt=0;attempt<90;attempt++){if(server.exitCode!==null)throw new Error("Local Next server exited");try{const response=await fetch(origin);if(response.ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,500));}
 assert.ok(ready,"Local server must start");
 for(const [name,engine] of [["chromium",chromium],["webkit",webkit]]){
  const browser=await engine.launch({headless:true});
  try{
   const page=await browser.newPage({viewport:{width:360,height:780}});
   await page.route("**/api/contributions/points",route=>route.fulfill({json:{points:3}}));
   const browserErrors=[];page.on("pageerror",error=>browserErrors.push(error.message));
   page.on("console",message=>{if(message.type()==="error")console.log(name,message.text());});
   page.on("response",response=>{if(response.status()>=400)console.log(name,response.status(),response.url());});
   page.setDefaultTimeout(10000);
   await page.goto(`${origin}/sign-in`);
   const signInButton=page.getByRole("button",{name:"Sign in",exact:true}),signupButton=page.getByRole("button",{name:"Create account",exact:true});
   for(const button of [signInButton,signupButton]){const box=await button.boundingBox();assert.ok(box.width>240&&box.height>=48);}
   assert.equal(await signInButton.getAttribute("value"),"signin");assert.equal(await signupButton.getAttribute("value"),"signup");
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,"Sign-in page must fit mobile");
   await page.setViewportSize({width:1000,height:780});
   assert.ok((await signInButton.boundingBox()).width>300);
   await mkdir("/Users/sylvester/Documents/Codex/2026-10-07/con/outputs",{recursive:true});
   if(name==="chromium")await page.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-sign-in.png"});
   await page.setViewportSize({width:360,height:780});
   await page.getByRole("link",{name:"Forgot password?",exact:true}).click();
   await page.getByRole("heading",{name:"Forgot password?",exact:true}).waitFor();
   await page.route("**/auth/password",route=>route.fulfill({status:200,contentType:"text/html",body:"<p>If an account exists for that email, a reset link has been requested.</p>"}));
   await page.getByLabel("Email",{exact:true}).fill("fixture@example.test");
   await page.getByRole("button",{name:"Send reset link",exact:true}).click();
   await page.getByText(/If an account exists for that email/).waitFor();
   let kind="guest",hasSections=false,holdRefresh=false,refreshRoute=null;
   const recorded={signedRules:[{label:"2P · Mon–Fri only · 8am–6pm",active:false},{label:"Saturday parking rule",active:true}],sectionId:"fixture-2p",geometryVersion:1,streetName:"Invented test street",side:"left",startDescription:"Fixture A",endDescription:"Fixture B",geometry:{type:"LineString",coordinates:[[145.05914649,-37.8869646],[145.05914649,-37.8859646]]},eligibility:"eligible_paid",reasonCodes:["paid_period"],explanation:"Payment required",earliestTransition:null,confidenceLevel:3,lastVerifiedAt:"2026-10-08T00:00:00Z",sourceDates:[],parkingDisplay:{category:"medium",payment:"paid",maxDurationMinutes:120,stayExceeded:false}};
   await page.route("**/api/session",route=>route.fulfill({json:{kind,userId:kind==="guest"?null:"00000000-0000-0000-0000-000000000081",reason:"verified"}}));
   await page.route("**/api/map/preview?*",route=>route.fulfill({json:{sections:[recorded],stay:{arrival:"2026-10-09T00:00:00Z",departure:"2026-10-09T00:15:00Z"},loadedAt:"2026-10-09T00:00:00Z"}}));
   await page.route("**/api/drafts",route=>route.fulfill({json:route.request().method()==="POST"?{saved:true,published:false}:{drafts:[]}}));
   await page.route("**/api/map/sections?*",route=>{if(holdRefresh){refreshRoute=route;return;}return route.fulfill({json:{sections:hasSections?[recorded]:[],message:hasSections?null:"No matching verified parking sections"}});});
   await page.route("https://tile.openstreetmap.org/**",async route=>route.fulfill({contentType:"image/png",body:await readFile("tests/browser/fixtures/tile.png")}));
   await page.goto(origin);
   await page.getByText("Town-centre preview · approved parking rules · 15-minute visit",{exact:true}).waitFor();
   assert.equal(await page.getByLabel("Search streets",{exact:true}).count(),0);
   await page.getByRole("link",{name:"Sign in to search locations",exact:true}).waitFor();
   assert.equal(await page.getByRole("form",{name:"Section annotation"}).count(),0);
   await page.getByRole("region",{name:"Parking map",exact:true}).waitFor();
   assert.equal(await page.getByLabel("Longitude",{exact:true}).count(),0);
   assert.equal(await page.getByText("Carnegie pilot",{exact:true}).count(),1);
   const mapCanvas=page.locator(".maplibregl-canvas");
   await mapCanvas.waitFor();await page.waitForTimeout(1200);
   assert.equal(await page.getByRole("button",{name:"Zoom in",exact:true}).count(),0);
   await mapCanvas.hover();await page.mouse.wheel(0,-400);
   await page.getByRole("link",{name:"Sign in to enable zoom",exact:true}).waitFor();
   await page.getByRole("button",{name:"Dismiss zoom notification"}).click();
   await mapCanvas.dispatchEvent("touchstart",{touches:[{identifier:0},{identifier:1}]});
   await page.getByRole("link",{name:"Sign in to enable zoom",exact:true}).waitFor();
   await page.getByRole("button",{name:"Dismiss zoom notification"}).click();
   const guestCanvas=await mapCanvas.boundingBox();
   await page.mouse.move(guestCanvas.x+guestCanvas.width*.8,guestCanvas.y+guestCanvas.height*.8);await page.mouse.down();
   await page.mouse.move(guestCanvas.x+guestCanvas.width*.2,guestCanvas.y+guestCanvas.height*.6,{steps:20});await page.mouse.up();
   await page.getByRole("link",{name:"Sign in to explore beyond the town centre",exact:true}).waitFor();
   kind="eligible";await page.reload();
   await page.getByRole("link",{name:"Change password",exact:true}).waitFor();
   assert.equal(await page.locator(".map-toolbar").evaluate(el=>el.open),false,"Signed-in dropdown controls collapse by default");
   await page.locator(".map-toolbar > summary").click();
   assert.equal(await page.getByLabel("Duration in minutes",{exact:true}).inputValue(),"15");
   await page.locator(".stay-panel-close").click();
   await page.getByText("Record a parking sign",{exact:true}).click();
   await page.getByRole("button",{name:"Use detailed editor",exact:true}).click();
   await page.getByRole("form",{name:"Section annotation"}).waitFor();
   await page.getByRole("button",{name:"Add sign panel",exact:true}).click();
   await page.getByLabel("Exact sign text").fill("2P 9am–5pm Mon–Fri");
   await page.getByRole("button",{name:"Add parking rule",exact:true}).click();
   await page.getByLabel("Rule type",{exact:true}).selectOption("time_limit");
   await page.getByLabel("Maximum stay",{exact:false}).fill("120");
   await page.getByRole("button",{name:"Add active period",exact:true}).click();
   await page.getByLabel("Start time",{exact:true}).fill("09:00");
   await page.getByRole("button",{name:"Save incomplete draft",exact:true}).click();
   await page.getByText("Saved to your account and this browser. Not published.",{exact:true}).waitFor();
   assert.equal(await page.getByRole("button",{name:"Submit complete annotation"}).isDisabled(),true);
   await page.reload();await page.locator(".map-toolbar > summary").click();await page.locator(".stay-panel-close").click();await page.getByText("Record a parking sign",{exact:true}).click();if(await page.getByRole("button",{name:"Use detailed editor",exact:true}).count())await page.getByRole("button",{name:"Use detailed editor",exact:true}).click();await page.getByLabel("Exact sign text").waitFor();
   assert.equal(await page.getByLabel("Exact sign text").inputValue(),"2P 9am–5pm Mon–Fri");
   assert.equal(await page.getByLabel("Maximum stay",{exact:false}).inputValue(),"120");
   await page.locator(".draft-backups summary").click();
   const previousDraft=await page.getByLabel("Saved sign drafts",{exact:true}).inputValue();
   await page.getByRole("button",{name:"Start another sign draft",exact:true}).click();
   await page.getByRole("button",{name:"Add sign panel",exact:true}).click();
   await page.getByLabel("Exact sign text").fill("No stopping");
   await page.getByLabel("Saved sign drafts",{exact:true}).selectOption(previousDraft);
   assert.equal(await page.getByLabel("Exact sign text").inputValue(),"2P 9am–5pm Mon–Fri");
   await page.getByRole("button",{name:"Retry",exact:true}).click();
   await page.getByText("Help map local parking — add the first signs.",{exact:true}).waitFor();
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
   await page.getByLabel("Search streets",{exact:true}).fill("Woorayl");
   await page.locator(".street-search-results button").first().waitFor();
   assert.deepEqual(await page.locator(".street-search-results button").allTextContents(),["Woorayl Street"],"Search shows one clean road name across both sides and sections");
   await page.getByLabel("Search streets",{exact:true}).fill("");
   const suburbNames=["Chadstone","Bentleigh","Brighton","Malvern","Oakleigh","Clayton","Springvale","Mulgrave","Clayton South","Moorabbin","Hampton","St Kilda","Glen Waverley"];
   const originalCanvas=await page.locator(".maplibregl-canvas").elementHandle();
   for(const suburb of suburbNames){
    await page.getByLabel("Suburb",{exact:true}).selectOption({label:suburb});
    await page.getByText(`${suburb} pilot`,{exact:true}).waitFor();
    const source=await page.request.get(`${origin}/coverage/${suburb.toLowerCase().replaceAll(" ","-")}.json`);assert.equal(source.status(),200);assert.ok((await source.json()).features.length>500);
   }
   assert.equal(await originalCanvas.evaluate(canvas=>canvas.isConnected),true,"Suburb switching must reuse the map canvas");
   await page.getByLabel("Suburb",{exact:true}).selectOption("carnegie");
   let addressCalls=0;
   await page.route("**/api/search/address?*",route=>{addressCalls++;return route.fulfill({json:{results:[{label:"123 Example Road, Carnegie, Melbourne",center:[145.05914649,-37.8864646]}]}});});
   await page.getByLabel("Search streets",{exact:true}).fill("123 Example Road");
   assert.equal(addressCalls,0,"Address lookup must wait for explicit submission");
   await page.getByRole("button",{name:"Search address",exact:true}).click();
   const addressButton=page.getByRole("button",{name:"123 Example Road, Carnegie, Melbourne",exact:true});
   await addressButton.waitFor();assert.equal(addressCalls,1);
   await addressButton.click();assert.equal(await page.getByLabel("Search streets",{exact:true}).inputValue(),"");
   await page.getByLabel("Search streets",{exact:true}).fill("123 Example Road");
   await page.getByLabel("Search streets",{exact:true}).press("Enter");
   await addressButton.waitFor();assert.equal(addressCalls,1,"Repeated address lookups should reuse cached results");
   await page.getByLabel("Search streets",{exact:true}).fill("");
   const baseline=await page.request.get(`${origin}/carnegie-streets.geojson`);
   assert.equal(baseline.status(),200);
   assert.ok((await baseline.json()).features.length>100,"Pilot roads must be available without parking records");
   await page.getByText("Record a parking sign",{exact:true}).click();
   if(name==="chromium"){
    await mkdir("/Users/sylvester/Documents/Codex/2026-10-07/con/outputs",{recursive:true});
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-grey-streets.png"});
   }
   hasSections=true;
   await page.getByRole("button",{name:"Retry",exact:true}).click();
   await page.getByText("1 street section recorded in this area.",{exact:true}).waitFor();
   if(await page.locator(".map-toolbar").evaluate(element=>element.open))await page.locator(".map-toolbar > summary").click();
   await mapCanvas.scrollIntoViewIfNeeded();
   const refreshCanvas=await mapCanvas.boundingBox();
   holdRefresh=true;
   await page.mouse.move(refreshCanvas.x+refreshCanvas.width/2,refreshCanvas.y+refreshCanvas.height/2);
   await page.mouse.down();await page.mouse.move(refreshCanvas.x+refreshCanvas.width/2+20,refreshCanvas.y+refreshCanvas.height/2,{steps:5});await page.mouse.up();
   await page.waitForTimeout(1200);
   await page.locator(".map-refresh-notice").waitFor();
   assert.equal(await page.locator("[aria-label=\"Evaluated sections\"] li").count(),1,"Previously loaded section stays available");
   assert.ok(refreshRoute,"Refresh request is pending");
   holdRefresh=false;await refreshRoute.fulfill({status:503,json:{error:"fixture unavailable"}});
   await page.getByText(/Could not refresh parking rules/).waitFor();
   assert.equal(await page.locator("[aria-label=\"Evaluated sections\"] li").count(),1,"Previously loaded section stays available");
   await page.getByRole("button",{name:"Retry",exact:true}).click();
   await page.getByText("1 street section recorded in this area.",{exact:true}).waitFor();
   await page.locator(".map-toolbar > summary").click();
   let zoomSteps=0;
   while(zoomSteps<4&&!await page.getByText("Zoom in to view parking rules",{exact:true}).count()){
    await page.getByRole("button",{name:"Zoom out",exact:true}).click();zoomSteps++;
    await page.waitForTimeout(600);
   }
   await page.getByText("Zoom in to view parking rules",{exact:true}).waitFor();
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,"Zoom notice fits mobile");
   for(let step=0;step<zoomSteps;step++){
    await page.getByRole("button",{name:"Zoom in",exact:true}).click();await page.waitForTimeout(600);
   }
   await page.getByText("Zoom in to view parking rules",{exact:true}).waitFor({state:"hidden"});
   await page.getByText("1 street section recorded in this area.",{exact:true}).waitFor();
   await page.getByText("Parking colours",{exact:true}).click();
   for(const label of ["Below 1P","1P–under 2P","2P–under 4P","4P and above","Permit only","Magenta edge · metered / paid"])await page.getByRole("listitem").filter({hasText:label}).waitFor();
   await page.getByText("Street list (1)",{exact:true}).click();
   await page.getByRole("button",{name:/Invented test street/}).click();
   await page.getByRole("button",{name:"Close section details",exact:true}).waitFor();
   await page.getByLabel("Parking filter",{exact:true}).selectOption("long");
   await page.getByText("Street list (0)",{exact:true}).waitFor();
   await page.getByLabel("Parking filter",{exact:true}).selectOption("paid");
   await page.getByText("Street list (1)",{exact:true}).waitFor();
   await page.getByRole("button",{name:"Close section details",exact:true}).click();
   await page.getByText("Street list (1)",{exact:true}).click();
   if(name==="chromium"){await mkdir("/Users/sylvester/Documents/Codex/2026-10-07/con/outputs",{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-mobile.png"});}
   assert.equal(await page.getByText("Map unavailable; use the section list",{exact:true}).count(),0,"Map must load successfully");
   assert.deepEqual(browserErrors,[],"Browser must not report runtime errors");
   console.log(`${name}: map-first layout, guest gate, multiple retained drafts, empty coverage, mobile layout passed`);
   // Exercise the actual canvas hit testing with a deterministic road, not injected map state.
   const reviewPage=await browser.newPage({viewport:{width:1000,height:780}});
   await reviewPage.route("**/api/contributions/points",route=>route.fulfill({json:{points:3}}));
   let submitted=null,reviewed=false;
   await reviewPage.route("**/api/session",route=>route.fulfill({json:{kind:"admin",userId:"00000000-0000-0000-0000-000000000081",reason:"verified"}}));
   await reviewPage.route("**/api/drafts",route=>route.fulfill({json:{drafts:[]}}));
   await reviewPage.route("**/api/map/sections?*",route=>route.fulfill({json:{sections:[]}}));
   await reviewPage.route("https://tile.openstreetmap.org/**",async route=>route.fulfill({contentType:"image/png",body:await readFile("tests/browser/fixtures/tile.png")}));
   await reviewPage.route("**/api/annotations",route=>{submitted=route.request().postDataJSON();return route.fulfill({json:{id:"fixture-submission",submitted:true}});});
   await reviewPage.route("**/api/admin/reviews",route=>{if(route.request().method()==="POST"){const decision=route.request().postDataJSON();assert.equal(decision.decision,"approve");assert.equal(decision.reason,"");reviewed=true;return route.fulfill({json:{reviewed:true}});}return route.fulfill({json:{submissions:reviewed?[]:Array.from({length:2},(_,i)=>({id:i?"fixture-submission-two":"fixture-submission",section:indexed,payload:submitted,submitted_at:"2026-10-08T00:00:00Z",pilot_street_side:{street_name:submitted.streetName,side:submitted.side}}))}});});
   await reviewPage.goto(origin);
   await reviewPage.getByRole("link",{name:"Change password",exact:true}).waitFor();
   await reviewPage.locator(".map-toolbar > summary").click();
   await reviewPage.locator(".stay-panel-close").click();
   await reviewPage.getByLabel("Search streets",{exact:true}).fill("Woorayl");
   await reviewPage.getByRole("button",{name:"Woorayl Street",exact:true}).click();
   // Search only moves the map. Use a registered selection link for the form/review fixture.
   const indexed=JSON.parse(await readFile("public/coverage/bentleigh.json","utf8")).features[0];
   const region=JSON.parse(await readFile("public/coverage/manifest.json","utf8")).suburbs.find(item=>item.id==="bentleigh");
   await reviewPage.goto(`${origin}/?sectionId=${indexed.id}&longitude=${region.center[0]}&latitude=${region.center[1]}#annotations`);
   await reviewPage.locator("#annotations").getByText(`${indexed.properties.name} · ${indexed.properties.side} side ·`,{exact:false}).waitFor();
   assert.equal(await reviewPage.getByLabel("Suburb",{exact:true}).inputValue(),"bentleigh","Sign-in return must restore new-suburb coverage");
   await reviewPage.getByRole("button",{name:"Start another sign draft",exact:true}).click();
   const form=reviewPage.getByRole("form",{name:"Parking details",exact:true});await form.waitFor();
   const parkingCard=form.locator(".quick-entry-card").first();
   const holiday=parkingCard.getByRole("checkbox",{name:"These times also apply on public holidays",exact:true});
   assert.equal(await holiday.isChecked(),false);
   await parkingCard.getByRole("checkbox",{name:"No days listed on the sign (every day)",exact:true}).check();
   assert.equal(await holiday.isChecked(),true);
   assert.equal(await parkingCard.getByRole("checkbox",{name:"Monday",exact:true}).isDisabled(),true);
   await parkingCard.getByRole("checkbox",{name:"No days listed on the sign (every day)",exact:true}).uncheck();
   assert.equal(await holiday.isChecked(),false);
   await form.getByLabel("Parking limit",{exact:true}).fill("5 min");
   await parkingCard.getByRole("checkbox",{name:"Saturday",exact:true}).uncheck();
   await parkingCard.getByRole("checkbox",{name:"Sunday",exact:true}).uncheck();
   await holiday.check();
   await form.getByRole("button",{name:"Add special condition",exact:true}).click();
   const condition=form.locator(".quick-entry-card").last();
   await condition.getByRole("combobox",{name:"Special condition",exact:true}).selectOption("towaway");
   await condition.getByRole("checkbox",{name:"All day",exact:true}).uncheck();
   await condition.getByLabel("From",{exact:true}).fill("16:00");
   await condition.getByLabel("Until",{exact:true}).fill("18:00");
   assert.equal(await condition.getByRole("checkbox",{name:"These times also apply on public holidays",exact:true}).isChecked(),false);
   assert.equal(await holiday.isChecked(),true,"Special-condition edits retain the parking rule's own holiday setting");
   const confirmRules=form.getByRole("checkbox",{name:"I've checked the rules, special conditions and boundaries for this street side",exact:true});
   const sendForReview=form.getByRole("button",{name:"Submit for review",exact:true});
   await parkingCard.getByRole("checkbox",{name:"All day",exact:true}).uncheck();
   await parkingCard.getByLabel("From",{exact:true}).fill("08:00");await parkingCard.getByLabel("Until",{exact:true}).fill("18:00");
   await condition.getByLabel("From",{exact:true}).fill("08:00");
   await condition.getByRole("checkbox",{name:"These times also apply on public holidays",exact:true}).check();
   await confirmRules.check();
   await form.getByRole("alert").filter({hasText:"completely covered by special conditions"}).waitFor();
   assert.equal(await sendForReview.isDisabled(),true,"Contradictory permission cannot be submitted even after confirmation");
   await parkingCard.getByRole("checkbox",{name:"All day",exact:true}).check();
   await condition.getByLabel("From",{exact:true}).fill("16:00");
   await condition.getByRole("checkbox",{name:"These times also apply on public holidays",exact:true}).uncheck();
   assert.equal(await sendForReview.isDisabled(),true);
   assert.equal(await sendForReview.evaluate(el=>getComputedStyle(el).backgroundColor),"rgb(226, 232, 240)");
   assert.equal(await confirmRules.getAttribute("required"),"");
   assert.equal(await form.locator(".required-marker").innerText(),"*");
   await confirmRules.check();assert.equal(await sendForReview.isEnabled(),true);
   await confirmRules.uncheck();assert.equal(await sendForReview.isDisabled(),true);
   await confirmRules.check();
   await form.getByRole("button",{name:"Save draft",exact:true}).click();
   await reviewPage.reload();
   const restored=reviewPage.getByRole("form",{name:"Parking details",exact:true});await restored.waitFor();
   assert.equal(await restored.getByLabel("Parking limit",{exact:true}).inputValue(),"5 min");
   assert.equal(await restored.getByRole("checkbox",{name:"Sunday",exact:true}).first().isChecked(),false);
   assert.equal(await restored.getByLabel("From",{exact:true}).inputValue(),"16:00");
   assert.equal(await restored.locator(".quick-entry-card").first().getByRole("checkbox",{name:"These times also apply on public holidays",exact:true}).isChecked(),true);
   assert.equal(await restored.locator(".quick-entry-card").last().getByRole("checkbox",{name:"These times also apply on public holidays",exact:true}).isChecked(),false);
   await reviewPage.setViewportSize({width:360,height:780});
   assert.equal(await reviewPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,"Simple annotation fits mobile");
   if(name==="chromium"){await restored.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-simple-annotation.png"});await restored.locator(".quick-entry-card").first().screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-parking-days.png"});}
   await reviewPage.setViewportSize({width:1000,height:780});
   await restored.getByRole("button",{name:"Submit for review",exact:true}).click();
   await reviewPage.getByText(/Submitted for review. Reference:/).waitFor();
   await restored.getByRole("heading",{name:"Sent for review",exact:true}).waitFor();
   assert.equal(await restored.locator(".submission-confirmation").evaluate(el=>el===document.activeElement),true);
   assert.equal(await restored.getByRole("button",{name:"Sent for review ✓",exact:true}).count(),1);
   if(name==="chromium")await restored.locator(".submission-confirmation").screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-submitted-for-review.png"});
   await restored.getByLabel("Parking limit",{exact:true}).first().fill("1 min");
   assert.equal(await restored.locator(".submission-confirmation").count(),0);
   assert.equal(await restored.getByRole("button",{name:"Submit for review",exact:true}).count(),1);
   assert.equal(submitted.sectionId,indexed.id);assert.equal(submitted.side,indexed.properties.side);
   assert.equal(submitted.schedule.rules.length,2);assert.equal(submitted.schedule.rules[1].type,"towaway");
   assert.equal(submitted.schedule.rules[0].source.evidenceKind,"community_entry");
   assert.equal(submitted.schedule.rules[0].maxDurationMinutes,5);
   assert.ok(submitted.schedule.rules[0].periods.every(p=>p.dayOfWeek!==0&&p.dayOfWeek!==6));
   assert.equal(submitted.schedule.rules[0].holidayPolicy,"applies");assert.equal(submitted.schedule.rules[1].holidayPolicy,"excluded");
   assert.equal(await form.locator('input[type="file"]').count(),0);
   await reviewPage.getByRole("link",{name:"Review annotations",exact:true}).click();
   await reviewPage.getByRole("img",{name:/Map of .*between boundaries A and B/}).first().waitFor();
   await reviewPage.setViewportSize({width:360,height:780});
   assert.equal(await reviewPage.locator(".review-outline").count(),2);
   assert.equal(await reviewPage.locator(".review-map .maplibregl-canvas").count(),0,"Queue starts without WebGL maps");
   assert.equal(await reviewPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,"Review page fits mobile");
   await reviewPage.getByRole("button",{name:"Show interactive map",exact:true}).first().click();
   await reviewPage.locator(".review-map .maplibregl-marker").first().waitFor();
   assert.equal(await reviewPage.locator(".review-map .maplibregl-canvas").count(),1);
   await reviewPage.route("**/map-style.json",route=>route.fulfill({status:503,json:{error:"fixture map failure"}}));
   await reviewPage.getByRole("button",{name:"Show interactive map",exact:true}).click();
   await reviewPage.getByText("Interactive map could not load. The road outline and Street View links remain available.",{exact:true}).waitFor();
   assert.equal(await reviewPage.locator(".review-map .maplibregl-canvas").count(),1,"Only one GPU map at a time");
   assert.equal(await reviewPage.getByRole("img",{name:/Map of .*between boundaries A and B/}).count(),2,"Geometry remains visible after map failure");
   if(name==="chromium")await reviewPage.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-review-mobile.png"});
   await reviewPage.getByRole("button",{name:"Hide interactive map",exact:true}).click();
   assert.equal(await reviewPage.getByRole("link",{name:/Street View ↗/}).count(),6);
   assert.ok(await reviewPage.getByText(/Monday ·/).count()>0);
   assert.equal(await reviewPage.getByLabel("Review reason (optional)",{exact:true}).first().inputValue(),"");
   assert.equal(await reviewPage.getByRole("button",{name:"Approve and publish",exact:true}).first().isEnabled(),true);
   await reviewPage.getByRole("button",{name:"Approve and publish",exact:true}).first().click();
   await reviewPage.getByText("Annotation approved and published.",{exact:true}).waitFor();
   assert.equal(reviewed,true);await reviewPage.close();console.log(`${name}: registered-side annotation submission and admin review UI passed`);
   for(const mode of ["mobile","desktop"]){
    const popupPage=await browser.newPage({viewport:{width:mode==="mobile"?360:1000,height:780},hasTouch:mode==="mobile",isMobile:mode==="mobile"});
    const errors=[];popupPage.on("pageerror",error=>errors.push(error.message));
    let signedIn=true,recordedRoad=false;const viewportWidths=[];
    await popupPage.route("**/api/contributions/points",route=>route.fulfill({json:{points:3}}));
    await popupPage.route("**/api/session",route=>route.fulfill({json:{kind:signedIn?"eligible":"guest",userId:signedIn?"00000000-0000-0000-0000-000000000081":null,reason:"verified"}}));
    await popupPage.route("**/api/map/preview?*",route=>route.fulfill({json:{sections:[],stay:{arrival:"2026-10-09T00:00:00Z",departure:"2026-10-09T00:15:00Z"},loadedAt:"2026-10-09T00:00:00Z"}}));
    await popupPage.route("**/api/drafts",route=>route.fulfill({json:{drafts:[]}}));
    await popupPage.route("**/api/map/sections?*",route=>{const params=new URL(route.request().url()).searchParams;viewportWidths.push(Number(params.get("east"))-Number(params.get("west")));return route.fulfill({json:{sections:recordedRoad?[recorded]:[]}});});
    await popupPage.route("**/carnegie-sections.json",route=>route.fulfill({json:{type:"FeatureCollection",features:[{type:"Feature",id:"fixture-road",properties:{name:"Invented grey street"},geometry:{type:"LineString",coordinates:[[145.05914649,-37.8869646],[145.05914649,-37.8859646]]}}]}}));
    await popupPage.route("https://tile.openstreetmap.org/**",async route=>route.fulfill({contentType:"image/png",body:await readFile("tests/browser/fixtures/tile.png")}));
    await popupPage.route("**/coverage/glen-waverley.json",route=>route.fulfill({json:{type:"FeatureCollection",features:[{type:"Feature",id:"expanded-fixture-road",properties:{name:"Invented expanded street"},geometry:{type:"LineString",coordinates:[[145.164,-37.8812],[145.164,-37.8802]]}}]}}));
    async function openStreet(expected=recordedRoad?"Invented test street":"Invented grey street"){
     const canvas=popupPage.locator(".maplibregl-canvas");await canvas.waitFor();
     for(let attempt=0;attempt<30;attempt++){
      const box=await canvas.boundingBox(),sideDistance=attempt%2===0?6:Math.min(96,6+Math.ceil(attempt/2)*4);
      if(mode==="mobile")await popupPage.touchscreen.tap(box.x+box.width/2+(recordedRoad?-sideDistance:sideDistance),box.y+box.height/2-16);
      else await popupPage.mouse.move(box.x+box.width/2+(recordedRoad?-sideDistance:sideDistance),box.y+box.height/2-16);
      if(await popupPage.getByRole("region",{name:"Street parking information",exact:true}).getByRole("heading",{name:expected,exact:true}).isVisible())return;
      await new Promise(resolve=>setTimeout(resolve,450));
     }
     await popupPage.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-map-test-failure.png"});
     throw new Error(`${name} ${mode}: street popup did not open`);
    }
    await popupPage.goto(origin);await popupPage.getByRole("link",{name:"Change password",exact:true}).waitFor();await popupPage.getByRole("button",{name:"3 points",exact:true}).click();await popupPage.getByRole("dialog").waitFor();assert.ok((await popupPage.getByRole("dialog").innerText()).includes("Rewards for points are planned for the future"));await popupPage.getByRole("button",{name:"Got it",exact:true}).click();assert.equal(await popupPage.getByRole("dialog").isVisible(),false);await popupPage.locator(".map-toolbar > summary").click();await popupPage.locator(".maplibregl-canvas").waitFor();
    assert.equal(await popupPage.locator(".stay-filter").evaluate(element=>element.open),true,"Arrival and stay controls open by default");
    const stayPanel=popupPage.locator(".stay-panel");await stayPanel.waitFor();
    const panelBox=await stayPanel.boundingBox(),viewport=popupPage.viewportSize();
    assert.ok(panelBox.width>=280,"Stay panel must not inherit the narrow trigger width");
    assert.ok(panelBox.x>=0&&panelBox.x+panelBox.width<=viewport.width,"Stay panel must fit horizontally");
    assert.ok(panelBox.y+panelBox.height<=viewport.height,"Stay panel must fit vertically");
    assert.equal(await stayPanel.evaluate(element=>element.scrollWidth>element.clientWidth),false,"Stay form must not overflow horizontally");
    const closeStay=stayPanel.getByRole("button",{name:"Close",exact:true});
    assert.equal(await closeStay.evaluate(button=>{const box=button.getBoundingClientRect();return button.contains(document.elementFromPoint(box.x+box.width/2,box.y+box.height/2));}),true,"Close must receive taps above the map zoom controls");
    if(mode==="mobile")await closeStay.tap();else await closeStay.click();
    assert.equal(await popupPage.locator(".stay-filter").evaluate(element=>element.open),false,"Close dismisses the stay popup");
    await popupPage.locator(".stay-filter > summary").click();await stayPanel.waitFor();
    await stayPanel.getByLabel("Arrival in Melbourne",{exact:true}).fill("2026-10-10T10:00");
    await stayPanel.getByLabel("Duration in minutes",{exact:true}).fill("120");
    await popupPage.screenshot({path:`/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-stay-${mode}.png`});
    await stayPanel.getByRole("button",{name:"Use this stay",exact:true}).click();
    assert.equal(await popupPage.locator(".stay-filter").evaluate(element=>element.open),false,"Applying a stay closes the panel");
    await popupPage.getByText("Arrival & duration",{exact:true}).click();
    assert.equal(await stayPanel.getByLabel("Duration in minutes",{exact:true}).inputValue(),"120");
    await stayPanel.getByRole("button",{name:"Close",exact:true}).click();
    signedIn=false;await popupPage.reload();
    await popupPage.getByText("No approved rules in this town-centre preview yet. Sign in to contribute.",{exact:true}).waitFor();
    await popupPage.locator(".map-toolbar > summary").click();
    await openStreet();
    const popup=popupPage.getByRole("region",{name:"Street parking information",exact:true});
    assert.equal(await popup.getByRole("heading").innerText(),"Invented grey street");
    const signIn=popup.getByRole("link",{name:"Sign in to contribute parking details",exact:true});
    assert.ok((await signIn.getAttribute("href")).startsWith("/sign-in?next="));
    const streetView=popup.getByRole("link",{name:/Google Maps Street View/});
    const viewUrl=new URL(await streetView.getAttribute("href"));
    assert.equal(viewUrl.hostname,"www.google.com");assert.equal(viewUrl.searchParams.get("map_action"),"pano");
    if(mode==="desktop"){
     await streetView.hover();await popupPage.waitForTimeout(400);
     assert.equal(await popup.isVisible(),true,"Hover popup must remain available over its link");
     await streetView.focus();await popupPage.mouse.move(900,700);await popupPage.waitForTimeout(400);
     assert.equal(await popup.isVisible(),true,"Keyboard focus must retain the popup even after the pointer leaves");
     await popupPage.keyboard.press("Escape");assert.equal(await popup.count(),0);
    }else{
     await popupPage.screenshot({path:"/Users/sylvester/Documents/Codex/2026-10-07/con/outputs/ParkMel-street-popup.png"});
    }
    await popupPage.keyboard.press("Escape");
    const retainedCanvas=await popupPage.locator(".maplibregl-canvas").elementHandle();
    await popupPage.locator(".map-toolbar > summary").click();
    await popupPage.getByLabel("Suburb",{exact:true}).selectOption("glen-waverley");
    await popupPage.locator(".map-toolbar > summary").click();
    await openStreet("Invented expanded street");
    assert.equal(await retainedCanvas.evaluate(canvas=>canvas.isConnected),true,"New suburb overlay must render on the retained canvas");
    signedIn=true;await popupPage.reload();
    await popupPage.getByRole("link",{name:"Change password",exact:true}).waitFor();
    await popupPage.locator(".map-toolbar > summary").click();await popupPage.locator(".stay-panel-close").click();await popupPage.locator(".map-toolbar > summary").click();
    await popupPage.getByText("Help map local parking — add the first signs.",{exact:true}).waitFor();
    if(mode==="desktop"){
     const canvas=popupPage.locator(".maplibregl-canvas");await canvas.waitFor();
     await popupPage.locator(".maplibregl-cooperative-gestures").waitFor({state:"attached"});
     await popupPage.evaluate(()=>window.scrollTo(0,0));await canvas.hover();
     const before=viewportWidths.at(-1);await popupPage.mouse.wheel(0,250);await popupPage.waitForTimeout(500);
     assert.equal(viewportWidths.at(-1),before,"Ordinary wheel must not zoom the map");
     assert.ok(await popupPage.evaluate(()=>scrollY)>0,"Ordinary wheel scrolls the page");
     for(const key of ["Control","Meta"]){
      await popupPage.evaluate(()=>window.scrollTo(0,0));await canvas.hover();const width=viewportWidths.at(-1);
      await popupPage.keyboard.down(key);await popupPage.mouse.wheel(0,-400);await popupPage.keyboard.up(key);
      for(let attempt=0;attempt<30&&!(viewportWidths.at(-1)<width);attempt++)await popupPage.waitForTimeout(100);
      assert.ok(viewportWidths.at(-1)<width,`${key} + scroll zooms the signed-in map`);
     }
    }else assert.equal(await popupPage.locator(".maplibregl-cooperative-gestures").count(),0,"Mobile retains ordinary touch and pinch handlers");
    await popupPage.getByText("Help map local parking — add the first signs.",{exact:true}).waitFor();await openStreet();
    await popup.getByRole("link",{name:"Contribute parking details",exact:true}).click();
    await popupPage.getByRole("form",{name:"Parking details",exact:true}).waitFor();
    await popupPage.getByText("Record a parking sign",{exact:true}).click();
    recordedRoad=true;await popupPage.getByRole("button",{name:"Retry",exact:true}).click();
    await popupPage.getByText("1 street section recorded in this area.",{exact:true}).waitFor();
    await popupPage.evaluate(()=>window.scrollTo(0,0));await openStreet();
    if(recordedRoad){const popup=popupPage.getByRole("region",{name:"Street parking information",exact:true});assert.equal(await popup.locator(".signed-rule-inactive").textContent(),"2P · Mon–Fri only · 8am–6pm");assert.equal(await popup.locator(".signed-rule-active").textContent(),"Saturday parking rule");}
    await popup.getByRole("heading",{name:"Invented test street",exact:true}).waitFor();
    assert.ok((await popup.innerText()).includes("2P"));assert.ok((await popup.innerText()).includes("Metered / paid"));
    await popup.getByRole("button",{name:"View section details",exact:true}).click();
    await popupPage.getByRole("button",{name:"Close section details",exact:true}).waitFor();
    assert.deepEqual(errors,[],`${name} ${mode}: popup must not produce runtime errors`);
    await popupPage.close();console.log(`${name} ${mode}: grey contribution/Street View and coloured rule popup passed`);
   }
  }finally{await browser.close();}
 }
}finally{server.kill("SIGTERM");}
