import {beforeEach,describe,it,expect,vi} from "vitest";
import {NextRequest} from "next/server";
const auth=vi.hoisted(()=>({exchangeCodeForSession:vi.fn(),resetPasswordForEmail:vi.fn(),getUser:vi.fn(),updateUser:vi.fn(),signOut:vi.fn()}));
vi.mock("../../src/lib/server/auth",()=>({createRequestAuth:()=>({auth})}));
import {GET as recovery} from "../../src/app/auth/recovery/route";
import {POST} from "../../src/app/auth/password/route";
beforeEach(()=>{vi.clearAllMocks();auth.exchangeCodeForSession.mockResolvedValue({error:null});auth.resetPasswordForEmail.mockResolvedValue({error:null});auth.getUser.mockResolvedValue({data:{user:{email_confirmed_at:"2026-10-01"}},error:null});auth.updateUser.mockResolvedValue({error:null});auth.signOut.mockResolvedValue({error:null});});
function req(values:Record<string,string>,origin="https://parkmel.example"){return new NextRequest("https://parkmel.example/auth/password",{method:"POST",headers:{origin,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams(values)});}
describe("password recovery",()=>{
 it("exchanges a recovery code for the fixed password page and rejects broken links",async()=>{const response=await recovery(new NextRequest("https://parkmel.example/auth/recovery?code=fixture&next=https://evil.example"));expect(response.headers.get("location")).toBe("https://parkmel.example/reset-password");expect(auth.exchangeCodeForSession).toHaveBeenCalledWith("fixture");expect((await recovery(new NextRequest("https://parkmel.example/auth/recovery?error=expired"))).headers.get("location")).toContain("/forgot-password?message=expired");});
 it("rejects cross-origin requests before contacting Auth",async()=>{expect((await POST(req({action:"request",email:"fixture@example.test"},"https://evil.example"))).status).toBe(403);expect(auth.resetPasswordForEmail).not.toHaveBeenCalled();});
 it("requests a PKCE link with a fixed same-origin reset destination and private cookies",async()=>{const response=await POST(req({action:"request",email:"fixture@example.test",next:"https://evil.example"}));expect(auth.resetPasswordForEmail).toHaveBeenCalledWith("fixture@example.test",{redirectTo:"https://parkmel.example/auth/recovery"});expect(response.headers.get("location")).toContain("message=sent");expect(response.headers.get("cache-control")).toBe("private, no-store");});
 it("rejects malformed emails and masks provider failures",async()=>{await POST(req({action:"request",email:"bad"}));expect(auth.resetPasswordForEmail).not.toHaveBeenCalled();auth.resetPasswordForEmail.mockResolvedValue({error:{message:"private"}});expect((await POST(req({action:"request",email:"fixture@example.test"}))).headers.get("location")).toContain("unavailable");});
 it("requires a verified live session before changing password",async()=>{auth.getUser.mockResolvedValue({data:{user:null},error:null});expect((await POST(req({action:"update",password:"fixture-password",confirmation:"fixture-password"}))).headers.get("location")).toContain("expired");expect(auth.updateUser).not.toHaveBeenCalled();});
 it("rejects mismatches and updates only the authenticated user's password",async()=>{await POST(req({action:"update",password:"fixture-password",confirmation:"other"}));expect(auth.updateUser).not.toHaveBeenCalled();const response=await POST(req({action:"update",password:"fixture-password",confirmation:"fixture-password",userId:"other"}));expect(auth.updateUser).toHaveBeenCalledWith({password:"fixture-password"});expect(auth.signOut).toHaveBeenCalled();expect(response.headers.get("location")).toContain("password_updated");});
});
