"use client";
import dynamic from "next/dynamic";
import {displayPeriod} from "../../domain/parking/display-time";
import type {StreetSide} from "../../lib/map/street-index";
const ReviewSectionMap=dynamic(()=>import("../../components/map/ReviewSectionMap"),{ssr:false,loading:()=> <p>Loading road preview…</p>});
import Link from "next/link";
import {useEffect,useState} from "react";
import type {AnnotationDraft} from "../../domain/community/draft";
import type {ParkingSchedule} from "../../domain/parking/types";
interface Review {section?:StreetSide|null;id:string;payload:AnnotationDraft;submitted_at:string;pilot_street_side:{street_name:string;side:string;start_description:string;end_description:string}}
export default function AdminPage(){
 const [activeMap,setActiveMap]=useState<string|null>(null);
 const [items,setItems]=useState<Review[]>([]),[message,setMessage]=useState("Loading review queue…"),[reasons,setReasons]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 async function load(){try{const response=await fetch("/api/admin/reviews",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.submissions);setMessage(body.submissions.length?"":"No pending annotations.");}catch(error){setMessage(error instanceof Error?error.message:"Review queue unavailable");}}
 useEffect(()=>{void load();},[]);
 async function review(id:string,decision:string){setBusy(true);try{const response=await fetch("/api/admin/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,decision,reason:reasons[id]??""})}),body=await response.json();if(!response.ok)throw new Error(body.error);await load();setMessage(`Annotation ${decision==="approve"?"approved and published":"rejected"}.`);}catch(error){setMessage(error instanceof Error?error.message:"Review failed");}finally{setBusy(false);}}
 return <main className="pilot"><Link href="/">← Parking map</Link><h1>Review parking annotations</h1><p>Check the entered limits, days, hours, special conditions and both boundaries before approving. A sign photo is not required. Approval publishes this side’s rules; it does not imply that every bay is available.</p><p role="status">{message}</p>{items.map(item=><section className="pilot-card" key={item.id}><h2>{item.pilot_street_side.street_name} · {item.pilot_street_side.side} side</h2><p>{item.payload.startDescription} → {item.payload.endDescription}</p><p>Submitted {new Date(item.submitted_at).toLocaleString("en-AU",{timeZone:"Australia/Melbourne"})} (Melbourne time)</p>{item.section?<ReviewSectionMap section={item.section} interactive={activeMap===item.id} onToggle={()=>setActiveMap(current=>current===item.id?null:item.id)}/>:<p>Road preview unavailable. Check both boundary descriptions before approving.</p>}<details><summary>Original entry and sign text</summary>{item.payload.panels.map(panel=><blockquote key={panel.id}>{panel.text} · arrow {panel.arrow}</blockquote>)}</details>{(item.payload.schedule as ParkingSchedule).rules.map(rule=><div key={rule.id}><p>{rule.type.replaceAll("_"," ")} · {rule.maxDurationMinutes??"no specified"} minutes · {rule.feeStatus} · holidays {rule.holidayPolicy} {rule.extent&&` · local ${rule.extent.start*100}–${rule.extent.end*100}%`}</p><p>Evidence {rule.source.evidenceKind} · image {rule.source.sourceDate??"not applicable"} · observed {rule.source.observedAt}</p>{rule.source.reference&&<p>{rule.source.reference}</p>}<ul>{rule.periods.map((period,index)=><li key={index}>{displayPeriod(period)}</li>)}</ul></div>)}<label>Review reason (optional)<textarea maxLength={2000} value={reasons[item.id]??""} onChange={event=>setReasons({...reasons,[item.id]:event.target.value})}/></label><button disabled={busy} onClick={()=>void review(item.id,"approve")}>Approve and publish</button><button disabled={busy} onClick={()=>void review(item.id,"reject")}>Reject</button></section>)}</main>;
}
